AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamodb-crud-app

  Sample SAM Template for dynamodb-crud-app

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs22.x
    MemorySize: 128
    Architectures:
      - x86_64
  
Resources:
  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Employees
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: empId
          AttributeType: S
      KeySchema: 
        - AttributeName: empId
          KeyType: HASH
    DeletionPolicy: Delete

  SeedEmployeesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: src/seed-employees/
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:PutItem"
              Resource: !GetAtt EmployeeTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref EmployeeTable

  FetchEmployeesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: src/fetch-employees/
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:Scan"
              Resource: !GetAtt EmployeeTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref EmployeeTable      

Outputs:
  EmployeeTableName:
    Description: "Employee Table Name"
    Value: !Ref EmployeeTable
  SeedEmployeesFunction:
    Description: "Seed Employees Lambda Function ARN"
    Value: !GetAtt SeedEmployeesFunction.Arn
  FetchEmployeesFunction:
    Description: "Fetch Employees Lambda Function ARN"
    Value: !GetAtt FetchEmployeesFunction.Arn


